# Generated by Django 5.0.2 on 2024-02-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
                'ordering': ('naziv',),
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'tip',
                'verbose_name_plural': 'tipovi',
                'ordering': ('naziv',),
            },
        ),
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('slika', models.ImageField(blank=True, upload_to='satovi/%Y/%m/%d')),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raspoloziv', models.BooleanField(default=True)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('azuriran', models.DateTimeField(auto_now=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satovi', to='ProdavnicaSatova.kategorija')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satovi', to='ProdavnicaSatova.tip')),
            ],
            options={
                'verbose_name_plural': 'satovi',
                'ordering': ('naziv',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
