# Generated by Django 5.0.2 on 2024-02-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdavnicaSatova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'brend',
                'verbose_name_plural': 'brendovi',
                'ordering': ('naziv',),
            },
        ),
        migrations.AddField(
            model_name='sat',
            name='brend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='satovi', to='ProdavnicaSatova.brend'),
            preserve_default=False,
        ),
    ]
