# Generated by Django 5.0.2 on 2024-02-07 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProdavnicaSatova', '0002_brend_sat_brend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.CharField(max_length=250)),
                ('postanski_broj', models.CharField(max_length=20)),
                ('grad', models.CharField(max_length=100)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_azuriranja', models.DateTimeField(auto_now=True)),
                ('placeno', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'porudzbina',
                'verbose_name_plural': 'porudzbine',
                'ordering': ('-datum_kreiranja',),
            },
        ),
        migrations.CreateModel(
            name='StavkaPorudzbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('porudzbina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_porudzbine_p', to='Porudzbina.porudzbina')),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_porudzbine_a', to='ProdavnicaSatova.sat')),
            ],
        ),
    ]
